# Generated by Django 2.2.17 on 2021-03-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Study',
        ),
    ]
