# Generated by Django 2.2.17 on 2021-04-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0004_auto_20210402_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
