# Generated by Django 2.2.17 on 2021-04-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
    ]
