# Generated by Django 3.1.7 on 2021-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0008_auto_20210402_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='blank_p_1.jpg', null=True, upload_to=''),
        ),
    ]
