# Generated by Django 3.1.7 on 2021-04-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0009_auto_20210403_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scishare.category')),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scishare.study')),
            ],
        ),
    ]
