# Generated by Django 2.2.17 on 2021-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0010_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='blank_p_1.jpg', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
