# Generated by Django 2.2.17 on 2021-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0011_auto_20210404_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='blank_p_1.jpg', upload_to=''),
        ),
    ]
