# Generated by Django 2.2.17 on 2021-04-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scishare', '0012_auto_20210404_1719'),
        ('scishare', '0011_auto_20210404_1652'),
    ]

    operations = [
    ]
